### ISSUE TITLE
Installing Vegas into the Kernel

### ISSUE THREAD

**Issue by FA5I** [twosigma/beakerx_kernel_scala#2]
Hi, 

Is there a way to install Scala packages into BeakerX kernel for Scala? I can't see anything in the docs.

I know I can do it inline inside a cell, but I want it to be available without the download and install every time.

- I am using conda 
- Inside conda I have jupyter and BeakerX installed
- I would like to add the Vegas plotting package into Conda / BeakerX; [https://github.com/vegas-viz/Vegas](https://github.com/vegas-viz/Vegas)

Any guidance would be much appreciated

**Comment by jaroslawmalekcodete** [comment]
Hi @acse-fk4517 
the beakerx approach to adding third-party libraries is done using magic command like:
```
%classpath add jar ../Downloads/vegas_2.11-0.3.11.jar
```
or 
```
%%classpath add mvn ....
```
and then importing things from this jar
in the same way like here https://nbviewer.jupyter.org/github/aishfenton/Vegas/blob/master/notebooks/jupyter_example.ipynb
